version: '3'
services:

  api:
    build:
      context: ../../../
      dockerfile: src/main/resources/Dockerfile
    command: catalina.sh run
    restart: unless-stopped
    ports:
      - "8090:8080"
    networks:
      mynetwokrk:
        ipv4_address: 10.5.0.6
  api_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=admin
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8081"
